// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzkapgdbfbbpohiojssu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6a2FwZ2RiZmJicG9oaW9qc3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTc0MDEsImV4cCI6MjA3MDM5MzQwMX0.GleP1E7kKVEDVKAgWSD5aPnRO8h7aJYtitd32nh5mdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});